flux-framework/rfc

- spec_3.adoc
* Rename `cmbd` to `flux-broker`
* Reserve `FLUX_NODEID_UPSTREAM`
* Add `FLUX_MSGFLAG_UPSTREAM`
> rfc3: update CMB1 protocol after broker refactor

- Makefile
- README.adoc
- spec_7.adoc
There was some  discussion in PR flux-framework/flux-core#205 about names for function pointer typedefs.
I'm proposing that we add SHOULD-level guidelines for
* lower case C variable names
* upper case C preprocessor macros
* non-function typedefs: lower case ending in `_t`
* function typedefs: lower case ending in `_f` and defined as function pointers
* use typedef pointer to incomplete type to publicly define abstract data types
> rfc7: add std for variable names and typedefs

- Makefile
- README.adoc
- spec_7.adoc
Although we still have prominent examples in our code (e.g. `flux_t`), I believe we concluded in PR #219 that abstract types should not obscure the fact that they are a pointer.
> update rfc7 abstract type rule

- spec_7.adoc
We should mention our decision to follow C99 in RFC 7.
> rfc7: Flux C programs should conform to C99

- Makefile
- README.adoc
- spec_10.adoc
Here is an RFC for the protocol used by the content service described in PR flux-framework/flux-core#493
Differences from the PR as it exists at this moment:
* PR blobrefs are not yet sent as message payloads; we are hardwiring SHA1 raw digests at the moment
* Asking the enclosing instance to resolve unknown blobrefs is not yet implemented
* Foreign blobrefs not yet implemented
I was going to describe JSON structures for representing ordered lists and hashmaps of (blobref, type) tuples which could then be used to construct structured content like the KVS namespace, but that was not getting quite off the ground so I would like to propose getting this in now and deferring that until work on the KVS gets underway again.
> rfc10: add spec for content storage service

- spec_10.adoc
Describe the distributed cache implementation briefly at the beginning
of the implementation section.  The dropcache and flush operations
don't really make a lot of sense without this context.
Mention an OPTIONAL backing store, but punt on the details, calling
it out of scope for this RFC.
Define more closely what flush does, and make it mandatory.
Define more closely what dropcache does, make it mandatory,
and limit when ENOSYS can be returned.
Fix a couple spelling errors.
> rfc10: add implementation overview, misc cleanup

- spec_10.adoc
I changed the description of blobrefs to be lower case per discussion, but forgot to update the example.
> rfc10: fix blobref example

- spec_1.adoc
As discussed in flux-framework/distribution#8, this PR adds a section called Release Process to RFC 1, and requires that framework projects use semantic versioning.  I also added a requirement for git annotated tags, and dist tarballs (if applicable).
> rfc1: add a Release Process section

- spec_3.adoc
- spec_5.adoc
As discussed in flux-framework/flux-core#181 and implemented in PR flux-framework/flux-core#640, JSON payloads should be encoded as JSON objects.  Bare arrays or scalar values are not allowed.
> Restrict JSON payloads to JSON object

- spec_4.adoc
Implements the changes to the Flux Resource Model that were discussed
in: https://github.com/flux-framework/flux-sched/issues/157
> spec_4:  Disambiguate basename and name

- spec_6.adoc
A few mods to RFC6 (Flux RPC protocol)
* Minor cleanup
* Allow an RPC to have zero or one response, rather than just one
* Describe "group RPC" and the allocation of the upper 12 matchtag bits as a group id, as implemented in flux-framework/flux-core#687
Left for another time:
* allowing for multiple responses per request
* more precise cancellation protocol (see flux-framework/flux-core#688)
> RFC6: add matchtag group description, cleanup

- spec_3.adoc
- spec_5.adoc
Update RFC 5 with the goal of:
* begin a process of iterating to bring sched plugins in line with RFC 5 or vice versa as discussed in flux-framework/flux-sched#125
* return errors in module initialization to `flux module load` as described in flux-framework/flux-sched#13
* provide low-level, single broker basis for future distributed synchronization of module init as touched on in flux-framework/flux-core#585
* enhancing module debug capability
The basis for most of this is an idea that keepalive messages could be used to inform the broker of module state transitions such as initializing -> [ready <-> busy] -> finalizing -> exited.
> RFC 3, 5: keepalives to communicate module state with broker

- spec_13.adoc
- spell.en.pws
This PR includes some cleanup and expansion of the PMI-1 RFC.
I tried to emphasize the concept of PMI as a tool for decoupling process managers and MPI runtimes, since it seems that this has been weakly achieved at best, despite a pretty good design IMHO.
I went out on a limb and suggested that a new environment variable PMI_LIBRARY be set to the path to a process manager's library, similer to Intel's I_MPI_PMI_LIBRARY environment variable.
> Further work on RFC 13

- spec_13.adoc
- spell.en.pws
This pr converts the kind of lame wire proto doc to ABNF, and changed a bit after cross-checking with the MPICH sources.
> rfc13: express wire proto in ABNF

- spec_13.adoc
- spell.en.pws
After trying to reconcile the Flux PMI wire protocol
implementation the ABNF defined here, it seems it was too
rigidly defined.  Relax a few things such as:
* Note that a parser should allow key=value tuples in any order,
extra whitespace, and extra keys without proto error.
* Make rc=N error responses optional
Also place a bit less emphasis on the library implementation,
which is more and more seeming like a legacy issue.
> rfc13: make rc=N optional in responses

- Makefile
- README.adoc
- spec_14.adoc
- spell.en.pws
As discussed in pr #29 and in our meeting today, here's a skeletal jobspec RFC redone in asciidoc, with a new number assigned.  I made @trws the editor.
I added an overview section which might be a little bit off the main focus of this document.  Happy to iterate to get it right.  Same with the goals section (I undoubtedly missed some or added some non-goals so please scrutinize).
The only bit I brought over from pr #29 was the terminology.  That wasn't due to a conscious exclusion of the other material - just trying to stick to the plan of submitting a template plus intro and leaving the hard work to other pr's.
> rfc14: add skeletal canonical job spec

- spec_14.adoc
- spell.en.pws
Based on our meeting yesterday I took an initial stab at fleshing out some of the *Jobspec Language Definition* section. I'm not too happy with what's here, but maybe this can generate some discussion and we can get an initial version merged today?
> Initial stab jobspec language definition

- spec_2.adoc
Replace the incorrect flux-devel@lists.llnl.gov with the correct
flux-discuss@lists.llnl.gov.
Fixes #57
> rfc2: Fix mailing list name

- spec_4.adoc
There appears to be a formatting error here.
> Allocate (N, S):: Allocate _N_ resources from the pool under the name _S. The available resources in 
> a pool is its size minus the total number of allocations. The allocation _S SHALL be stored as a 
> searchable attribute along with the resource for later use with _Find_ and _Match_ methods. If an
> allocation under _S already exists, then the allocation SHALL be grown by amount _N_.
I don't think the variable ```_S``` or method ```_Find``` is intended.
> rfc4: Fix italics formatting error

- spec_4.adoc
Description states ```string``` while prototype lists ```S```.
> rfc4: Fix variable name in description to match method prototype

- spec_14.adoc
I don't think this paragraph is supposed to be indented further, I think it's supposed to be at the same level as the previous paragraph.
> rfc14: Fix paragraph identation

- Makefile
- spec_10.adoc
- spec_13.adoc
- spec_14.adoc
- spec_3.adoc
- spec_4.adoc
Add pdf make target that use a2x to convert asciidoc files
into pdf files.
a2x is using docbook, and docbook does not not like empty
sections or sections named "References".  We ad "TBD" to empty
sections to make them non-empty, and explicitly declare the
sections type as "[sect2]" for "== References" sections.
Note that an alternate way of dealing with the "References"
section name problem is to convert to using actual footnotes
and/or bibliography support in asciidoc.
> Add pdf make target for all docs

- spec_11.adoc
- spell.en.pws
See commit description.  This is a proposed change to the proposed KVS metadata format which I think may address the large directory performance problem we've observed and begun to work around.
Note that to try this out directly, the KVS will need to be converted the proposed format.  I will try to think of a way to test this idea out sooner using the old metadata format, but I'd be interested in any feedback on the general approach.
> rfc11: add hdir object type

- spec_3.adoc
Problem: the required "cmb." prefix on broker-resident
services makes it impossible to migrate the service
to a comms module without changing the protocol.
Drop this requirement.  The broker routing already uses
a service table rather than this tag to determine where
to route a given request message.  Indeed a large number
of broker-resident services have already dropped the cmb prefix.
> rfc3: drop "cmb." prefix from broker services

- spec_12.adoc
- spec_8.adoc
We want to leave the term "bootstrap" as a verb that descibes
the process of starting up process, providing their initial
configuration information, and performing network discovery.
Instead we call the long-lived multi-user instance that is one
of the primary parent instances in cluster or center a "system
instance".
Since exact details of the "system instance" architecture are still
a hotly debated topic (e.g. whether or not the system instance spans
both management and compute nodes as a single instance), we leave
the "Bootstrap Mechanism" of spec 8 to only descript bootstrapping,
not system instances.  We can describe system instances later
when we know what exactly they are.
> Replace the "bootstrap instance" term with "system instance".

- spec_4.adoc
Reorganize the structure of the Flux Resource Model to more closely mirror the requirements as they have evolved over the last couple years.  This helps prepare the way for migrating flux-sched/resrc into a standalone flux-resource project.
Focus the scope of this RFC by removing the specs to define resources requests.  Requesting resources will involve [RFC 14 - Canonical Job Specification](https://github.com/flux-framework/rfc/blob/master/spec_14.adoc) and will probably merit a dedicated RFC.
> RFC4 reorg

- spec_7.adoc
- spell.en.pws
Add new rule to require that typedef names be unique
accross a project (e.g. avoid using ctx_t in multiple places).
This change was suggested in issue #972.
> rfc7: Add rule about unique typedef names

- spec_14.adoc
The "Flux Task and Program Execution Services" RFC is
8, not 12.
> rfc14: Correct link in Related Standard section

- spec_4.adoc
This commit implements much of the discussion in (https://github.com/flux-framework/rfc/pull/76).
This involves two main changes:
* Eliminate aspects of the model that relate to scheduling operations
* Provide a distinct abstraction between a resource and any graphs to
which it is associated.  This includes the composite hierarchy.
Description of the composite hierarchy is retained, but becomes just
another graph.
Additional RFC's are planned to specify:
* Flux Resource Graph Model
* Flux Scheduling of Flux Resources Model
> rfc4:  Pare the RFC down to a simpler model

- spec_12.adoc
- spell.en.pws
This PR amends RFC 12 with the userid, rolemask, and user database concepts discussed in #72 and prototyped in flux-framework/flux-core#980.
I stated right at the beginning the assumption that POSIX UID's be synced across systems spanned by a Flux instance even though we discussed the possibility in #72 that non-synchronized systems might need to be handled at some point.  That's not strictly built in to the design, but it is assumed in a few places now, e.g. the local connector authenticates with SO_PEERCRED (directly mapping uid to Flux userid), and some connectors compare `geteuid()` with the Flux userid to determine whether it's the instance owner.   The fact that we have defined a "Flux userid" separately from the POSIX UID most places except at these ingress points should make that …
> rfc12: add description of userid, rolemask based security

- spec_14.adoc
Overhaul the examples to better match the canonical jobspec, so we
have a foundation to debate and improve the jobspec.
Honor the rule, "The dictionary MUST contain the keys `resources`, `tasks`,
`walltime`, `attrs`, and `version`" by adding missing keys.
Eliminate the assumed "tasks" section in the examples.  Instead directly
include complete examples so that the reader is not asked to make mental
substitutions.
Add "count" to any resource that previously had only a "type".  By canon,
resource SHALL contain both a type and a count.
Fixes #83
Fixes #86
> rfc14: Overhaul examples to better match the canonical jobspec

- spec_7.adoc
Ban the use of "_struct" in structure tags.
> rfc7: Ban the use of "_struct" in structure tags.

- spec_11.adoc
- spell.en.pws
_Note: This spec was proposed a while back but never implemented.  We're now getting around to that, and I'm working with @chu11 to refine the spec and work out implementation details.  Once we're further along, I'll write some descriptive text to document this better._
This PR proposes that KVS values be internally represented as unstructured, opaque data, rather than requiring them to be JSON.  The previous specification was kind of trying to have it both ways with the _value_ object that was JSON and a _valref_ object that referred to opaque data in the content store.
Note that API's won't have to change - the main API's can remain JSON oriented, but internally the KVS will treat values as opaque.  We'll add functions for accessing the raw data too so users won't have to layer on …
> represent KVS values internally as opaque data, and cleanup

- README.adoc
- spell.en.pws
I aborted pr #98 , but it contained two patches for RFC 15, one to add proper names to the dictionary as travis was failing for me, and one to make a link/abstract for it in the top level readme.  Here are those patches by themselves.
> misc RFC 15 cleanup

- data/spec_14/example1.yaml
- data/spec_14/example2.yaml
- data/spec_14/use_case_1.1.yaml
- data/spec_14/use_case_1.2.yaml
- data/spec_14/use_case_1.3.yaml
- data/spec_14/use_case_1.4.yaml
- data/spec_14/use_case_1.5.yaml
- data/spec_14/use_case_1.6.yaml
- data/spec_14/use_case_1.7.yaml
- data/spec_14/use_case_2.1.yaml
- data/spec_14/use_case_2.2.yaml
- data/spec_14/use_case_2.3.yaml
- data/spec_14/use_case_2.4.yaml
- data/spec_14/use_case_2.5.yaml
- data/spec_14/use_case_2.6.yaml
- spec_14.adoc
All of the jobspec yaml examples are broken out into individual
files.  This will make it easier to run each example through an
automated validator in the future.
> Break out examples

- Makefile
- README.adoc
- spec_16.adoc
- spell.en.pws
This PR adds a preliminary version (an incomplete rough draft really) of a "KVS Job Schema" RFC.  While I think it's probably a bit early to settle on fine details here, it's helpful now to anticipate how "instance components" (running as instance owner) and "guest components" (running as the the job submitter) of the system might use the KVS, as we approach new KVS features in the near term:
* flux-framework/flux-core#1197 KVS namespaces
* flux-framework/flux-core#1193 KVS atomic append
* flux-framework/flux-core#1185 KVS checkpoint restart
(The namespaces achieve two goals:  one, to decouple performance of the primary KVS namespace from commit activity within a job, and two, to provide coarse grained multi-user support in the KVS.  The atomic append would allow an "event log" or an I/O …
> rfc16: add KVS Job Schema RFC

- spec_16.adoc
Update kvs schema naming of *R* to remove the `-signed` suffix, since *R* is no longer required to be signed per latest RFC15.
> rfc16: replace R-signed with "R" in kvs schema

- spec_16.adoc
'/' delimiter in KVS filepath should be '.'
> rfc16: fix typo in KVS filepath

- spec_6.adoc
- spell.en.pws
This loosens RFC 6's definition of an RPC to allow for more than one response to a request.  This practice has been used in our code base for some time but never formalized.
My biggest concern about allowing this without some sort of open/close stream abstraction was the potential for a matchtag to be reused in another RPC, creating hard to find, intermittent bugs.  To address this concern, this PR proposes that clients and servers agree that any error response (no payload, errnum != 0) should signifiy the end of an RPC, and suggests that services could optionally use an error response of ENODATA as an EOF of sorts.
> rfc6: allow multiple RPC responses

- spec_3.adoc
- spec_6.adoc
This change allows RPC error responses to include a brief, human readable description of the error.
In addition, it clarifies evolving payload norms and drops the FLUX_MSGFLAG_JSON flag as proposed in #123.
> rfc3, rfc6: allow RPC error response string, clarify payloads

- spec_14.adoc
- spec_3.adoc
As noted in #120, the ABNF usage in RFC3 took some undocumented liberties.  Add a footnote to explain this.
Also, fix my cut and paste error in PR #125.
> rfc3: explain informal ABNF usage

- Makefile
- spec_16.adoc
- spec_18.adoc
- spell.en.pws
This RFC is a rough first cut at describing the KVS event log format used for job events.  The KVS event log is initially described in RFC16, but the event format was never defined.  This is the log format that @garlick, @grondo, and I settled on during an afternoon brainstorming session.
Closes #133
> RFC 18: KVS Event Log Format

- spec_18.adoc
Problem:  two items in bullet list were improperly merged.
Add missing asterisk.
> rfc18: fix formatting error

- spec_7.adoc
- spell.en.pws
This follows up on a discussion in flux-framework/flux-core#1668
> rfc7: forbid typedefs for fixed length arrays

- spec_5.adoc
Remove the optional `service_name` extension module symbol. It is
no longer used by the broker to determine a secondary service
name for modules.
(Assuming PR flux-framework/flux-core#1753 goes in)
> rfc5: remove service_name symbol

- spec_10.adoc
Problem: RFC 10 requires Flux instances to use the
enclosing instance, if any, as a tertiary level of
content storage.  This feature has not been implemented
and is not strongly motivated.
Change SHALL to MAY for this feature.
This was discussed in flux-framework/flux-core#1784
> rfc10: change SHALL to MAY for enclosing instance

- spec_2.adoc
- spell.en.pws
Now that we've decided to make flux-framework LGPL 3 (and received approval), RFC 2 needs an update.
> rfc2: update evolving stance on flux project licensing

- data/spec_14/use_case_1.3.yaml
- data/spec_14/use_case_2.5.yaml
- data/spec_14/use_case_2.6.yaml
- spec_14.adoc
This PR is meant to address the main issue brought up in #105, which I think
everyone agreed was valid and should be fixed in the RFC.
The description of Use Case 1.3 is worded with "at least", but the actual
example jobspec specified the exact count of sockets and cores. Update the
example to use a `min` count instead with no `max` (implying "at least").
Adjust the wording for the task `count` key to allow specification of `min`
without `max`, to make the new UC1.3 adhere to the spec.
Closes #105
> spec14: clarify UC1.3

- spec_16.adoc
- spell.en.pws
RFC 16 (job schema) had fallen behind the design of our execution system a bit.  I dropped the "job states" (events) listed at the top, and updated the description to better match the current design.  I suspect we'll change this a few more times as we work through the new system.
> rfc16: remove job states, sync with job manager design changes

- .mergify.yml
Maybe trying out mergify.io on the rfc project first will be more acceptable?
This PR adds an initial config file for mergify.io with strict merge enabled.
This config file enables the mergify bot to auto-rebase and merge
PRs once all of the following conditions are met:
- The label "merge-when-passing" is applied
- The label "work-in-progress" is not applied
- The PR title doesn't start with "[wip|WIP]" or "wip" or "WIP"
- Travis-CI checks pass
- There is at least one approving review by a member of flux team
- There are no outstanding changes requested.
> add config file for mergify autorebase/merge service

- data/spec_14/use_case_1.6.yaml
- data/spec_14/use_case_1.7.yaml
- spec_14.adoc
Adds `per_resource` option to a task's `count` key.
I noticed that at the top of the first section of examples (i.e., resource only requests), it states:
> In terms of a canonical jobspec, these requests are assumed to be requests to start an instance, i.e. run a single copy of flux start per allocated node.
But then use-cases 1.6 and 1.7 (1.6 and 1.8 in this PR), allocate and run `flux start` on a per-core basis.  Do we want to move those use-cases out of the `resource only requests` section of examples and into the 2nd section of examples?
Closes #150 
Closes #156
> RFC14: Add `per_resource` option to task's `count`

- Makefile
- README.adoc
- spec_22.adoc
- spell.en.pws
This RFC defines the (simple!) idset string format, so that other RFCs don't have to.  @grondo suggested it and I thought it was a good idea.
> rfc22: add idset string specification

- spec_20.adoc
- spell.en.pws
This PR addresses Issue #160. This allows the system to raise a `timelimit` exception on a job once it's outlived its wallclock limit.
> rfc20: Add starttime and expiration keys

- spec_20.adoc
As discussed in #161, allow multiple ranks per R_lite "entry" object to allow for condensed representation.
Also makes `node` an optional member of *R_lite* entries (not sure hostnames belong in R_lite anyway), and reference an TBD (to be drafted) RFC for the *idset* format.
Closes #161
> rfc20: allow multiple ranks per R_lite entry

- spec_16.adoc
This PR tidies up the job schema RFC.  The two substantive changes are:
* eliminating the `userid` and `priority` keys, as these are now in the eventlog
* renaming `J_signed` to `J`
The rest is cleanup and the addition of references.
> RFC 16: cleanup, fold priority and userid into eventlog

- spec_16.adoc
Just some small updates to the Job KVS Schema to bring the RFC in line with emerging reality:
- Update job lifecycle to indicate that exec system notifies job manager of "job shell exit" events which triggers the free of resources back to scheduler.
- Remove copies of `jobspec` and `R` from guest kvs namespace. It seems these copies are not needed once the kvs proxy service is in place.
- Note that the exec system will copy/link guest namespace into the main KVS namespace before notifying the job manager that the execution is "finished".
> rfc16: updates related to exec system, guest namespace

- spec_21.adoc
- spell.en.pws
Add detail regarding the events that the job manager logs to the primary job eventlog.
Back out the requirement that the event context use a `key=value [key=value...]` format, and use JSON instead so that we don't set ourselves on a path of reinventing yet another half-baked serialization format.
The transition to JSON was discussed in flux-framework/flux-core#2076
This is a rather big update but I would say the original draft was pretty drafty, and now that we've got some implementation out of the way, we can set more details down here.  There are still some changes required to support partial release of resources and reporting of global exit status, but I thought we are better off documenting what we have now and adding that later.
> rfc21: define the events that drive state transitions in more detail

- README.adoc
- spec_21.adoc
Update RFC 21 to add a `clean` event, used to indicate that CLEANUP state activities are over.
Also since the RFC now contains quite a lot of detail about job events, update the title to
_21/Job States and Events_.
Finally, I noticed we didn't mention that a job can have multiple exceptions.  Make that explicit.
> rfc21: change title, add clean event

- Makefile
- data/spec_14/schema.json
- spec_14.adoc
- spell.en.pws
As discussed in #172, this PR
* Specifically calls out that system and user attributes can have any value type
* Replaces JCR specification with json-schema from flux-core, which now allows any type
Change the Makefile to generate html using asciidoctor and coderay, which makes a much prettier rendering, with inline source includes expanded and highlighted.
Sadly:  github rendering of includes doesn't even produce a clickable link anymore.  We really need to consider those other document publishing options, time permitting.
> rfc14: allow attributes to have any value type

- spec_21.adoc
- spell.en.pws
This PR adds a `status` value to the `finish` event context, tracking development in flux-framework/flux-core#2077.
> rfc21: add context to finish event

- Makefile
- README.adoc
- spec_23.adoc
This PR adds a description of Flux Standard Duration:tm:, a common string duration format (as in GNU `sleep(1)`)
> rfc23: describe a common duration string format

- data/spec_14/example1.yaml
- data/spec_14/example2.yaml
- data/spec_14/use_case_1.1.yaml
- data/spec_14/use_case_1.2.yaml
- data/spec_14/use_case_1.3.yaml
- data/spec_14/use_case_1.4.yaml
- data/spec_14/use_case_1.5.yaml
- data/spec_14/use_case_1.6.yaml
- data/spec_14/use_case_1.7.yaml
- data/spec_14/use_case_2.1.yaml
- data/spec_14/use_case_2.2.yaml
- data/spec_14/use_case_2.3.yaml
- data/spec_14/use_case_2.4.yaml
- data/spec_14/use_case_2.5.yaml
- data/spec_14/use_case_2.6.yaml
- spec_14.adoc
Problem: RFC 14 specifies that the system attribute "duration" is
a "string representing a time span", but does not specify how that
string is to be interpreted.
Since this RFC describes a canonical jobspec format, specifically
state that the duration is a number of seconds, leaving no question
as to how it should be interpreted.
Update all use case examples that used arbitrary strings for duration.
Fixes #175
> rfc14: make duration attribute a number of seconds

- spec_14.adoc
As mentioned in flux-framework/flux-core#2096, the `duration` system attribute should have a minimum of `0`, where `0` (zero) itself is reserved for a special meaning of either "not set" or "unlimited".
After I wrote that I though perhaps "not set" could be represented by literally not setting the `duration` attribute. Should I change the wording here to state that zero means "unlimited" duration?
> rfc14: clarify duration attribute range and meaning

- spec_18.adoc
As discussed in #180, it's useful to require all events appended to Flux KVS Event Logs to be JSON objects, rather than the hybrid format we ended up with in the current job manager.  This PR makes that change to the event log RFC.
> RFC 18: require events to be JSON objects

- spec_16.adoc
- spec_21.adoc
Remove jobs.active and jobs.inactive directories, instead, all
job information will be listed under "jobs".
Adjust accordingly in rfc21 as well.
> rfc16: Remove jobs.active and jobs.inactive

- spec_23.adoc
- spell.en.pws
Clarify allowed fsd floats to correspond to changes in flux-framework/flux-core#2216.
> add non-infinite and non-NaN conditions to fsd

- spec_3.adoc
- spec_6.adoc
- spell.en.pws
This PR tracks changes proposed in flux-framework/flux-core#2153.
It defines the FLUX_MSGFLAG_STREAMING message flag in RFC 3, then describes how it is to be used in RPCs in RFC 6, including the conditions when a matchtag can be safely reclaimed.
> add FLUX_MSGFLAG_STREAMING

- Makefile
- README.adoc
- spec_24.adoc
- spell.en.pws
Here is a first go at defining a KVS eventlog format for standard I/O as discussed in #192.
> rfc24: add new RFC for KVS stdio format

- spec_24.adoc
- spell.en.pws
Add a new event type called "log" that is intended to capture flux-shell log messages as part of the job's output key.  Drop the "stdlog" stream, which was the first attempt at enabling logging, as log messages don't necessarily follow stream semantics.
> rfc24: add log event

- README.adoc
- spec_5.adoc
- spell.en.pws
As noted in #202, RFC 5 tried unsuccessfully to propose some common rules for all types of Flux plugins.   This design as described is incomplete, and better ideas have since been floated.  Some are under construction and consideration now, e.g. see
flux-shell plugin PR: flux-framework/flux-core#2357
shell plugin design issue:  flux-framework/flux-core#2266
earlier "extensor" PR attempt:  flux-framework/flux-core#930.
Since the info in RFC 5 is outdated, trim it down to only describe (in terms as stark as possible) the way that Flux "comms modules" currently work.  I purposefully kept the somewhat antiquated term.
When we move forward, we can create new RFCs and deprecate this one.
> RFC 5: rework to describe existing comms modules

- spec_18.adoc
It came up in flux-framework/flux-core#2374 that some basic rules of engagement for eventlogs had not been documented.  So this adds a little bit of clarification.
> rfc18: establish some basic eventlog update rules

- spec_24.adoc
Per discussion in https://github.com/flux-framework/flux-core/pull/2395 and https://github.com/flux-framework/flux-core/issues/2399
> rfc24: Add redirect event

- Makefile
- README.adoc
- data/spec_14/example1.yaml
- data/spec_14/example2.yaml
- data/spec_14/schema.json
- data/spec_14/use_case_1.1.yaml
- data/spec_14/use_case_1.2.yaml
- data/spec_14/use_case_1.3.yaml
- data/spec_14/use_case_1.4.yaml
- data/spec_14/use_case_1.5.yaml
- data/spec_14/use_case_1.6.yaml
- data/spec_14/use_case_1.7.yaml
- data/spec_14/use_case_2.1.yaml
- data/spec_14/use_case_2.2.yaml
- data/spec_14/use_case_2.3.yaml
- data/spec_14/use_case_2.4.yaml
- data/spec_14/use_case_2.5.yaml
- data/spec_14/use_case_2.6.yaml
- data/spec_14/use_case_2.7.yaml
- data/spec_25/example1.yaml
- data/spec_25/schema.json
- data/spec_25/use_case_1.1.yaml
- data/spec_25/use_case_2.1.yaml
- data/spec_25/use_case_2.2.yaml
- data/spec_25/use_case_2.3.yaml
- data/spec_25/use_case_2.4.yaml
- spec_14.adoc
- spec_25.adoc
- spell.en.pws
Still TODO:
I'm happy to split the environment and cwd changes out into a separate PR if desirable.
Closes #100
Closes #188 
Closes #149
> RFCs 14 & 25: Jobspec Version 1 + ENV and CWD attributes

- spec_24.adoc
This PR proposes a couple minor changes to the RFC 24 `log` event context.
Probably uncontroversial -- optional `file` `line` and `component` keys are added to the context. Addition of these members to log messages may aid in post mortem debugging.
(In case it isn't clear, the `component` would be used to indicate a facility or more likely plugin name which generated the log message)
Perhaps more controversial, I removed the reference to RFC 5424 severity levels and renamed the field to `level` instead of `severity`. The syslog severity system seems more tailored to system logs and not simple process logging, for which we'd like a more straightforward logging system that goes from "Fatal" errors to "Trace" logs. (For the shell my current implementation uses `0=Fatal, Error, Warning, Info, …
> rfc24: update log event context

- spec_24.adoc
After some prototyping and some discussion in https://github.com/flux-framework/flux-core/issues/2257, I realized that there are a number of scenarios where "rank" should refer to all tasks in the job.  For example, stdin is typically broadcast to all ranks.
It can be inconvenient to calculate what all ranks in a job are b/c you have to get the jobspec, parse it, and calculate the idset string.
This PR allows the special case string "all" to indicate all ranks in the job.  Obviously we can debate if it should be wildcare (`*`) or another string instead.
Note that I only added "all" on data events and not redirect events.  I didn't see a use case in the latter case yet.
> rfc24: Allow data rank to be set to "all"

- spec_24.adoc
As discussed in flux-framework/flux-core#2477, change the `rank` key in RFC 24 log event context from REQUIRED to OPTIONAL. If  the `rank` key is missing it is assumed the shell rank is unknown at the time of the log message.
This PR also adds another optional key: `program`, which is assumed to be `flux-shell` when not present, but could be used in the future if outside entities write log messages to a job output event log. It is assumed the that `program` value will be used as the prefix for log messages in display programs like `flux-job attach`.
> rfc24: log event context updates

- data/spec_14/example1.yaml
- data/spec_14/example2.yaml
- data/spec_14/schema.json
- data/spec_14/use_case_2.1.yaml
- data/spec_14/use_case_2.2.yaml
- data/spec_14/use_case_2.3.yaml
- data/spec_14/use_case_2.4.yaml
- data/spec_14/use_case_2.5.yaml
- data/spec_14/use_case_2.6.yaml
- data/spec_25/example1.yaml
- data/spec_25/use_case_2.1.yaml
- data/spec_25/use_case_2.2.yaml
- spec_14.adoc
Per discussion offline and in issue #213, update commands to always be a list, instead of possibly a list or string.
Update schema and examples accordingly.
> rfc14: Update commands to always be a list

- spec_14.adoc
My preliminary proposal for a `job-name` field in the jobspec.
> rfc14: Add system.job-name field description

- spec_6.adoc
The mrpc class is deprecated in flux-framework/flux-core#2612,
so we no longer need group matchtag bits.  It was a hack anyway.
> rfc6: drop group RPC section

- .travis.yml
- Makefile
- README.adoc
- data/spec_14/schema.json
- data/spec_14/use_case_2.8.yaml
- data/spec_26/example_1.yaml
- data/spec_26/example_2.yaml
- data/spec_26/example_3_A.yaml
- data/spec_26/example_3_B.yaml
- data/spec_26/example_3_C.yaml
- data/spec_26/schema.json
- spec_14.adoc
- spec_26.adoc
- spell.en.pws
- validate.py
Adds the OpenMP-inspired `in`, `out`, and `inout` keys as valid
dependency types.
Based on discussion in
https://github.com/flux-framework/flux-core/issues/1698
Closes #209
> rfc26: extend canonical jobspec to support job dependencies

- spec_7.rst
Header formatting missed by the rebase / conversion.
> Spec 7 header formatting

- README.md
- index.rst
This PR changes the title at the of README so that it will look better in the RTD website. 
The index.rst file is used by sphinx to make sure each page appears somewhere. We make the TOC tree hidden since we’ll use the README to list each sub-page for this repo.
> Rendering of Readme

- spec_3.rst
- spec_6.rst
flux-framework/flux-core#2913 introduced a new message flag.  This PR updates RFC 3 and 6 with the new flag.
It also updates the "cancellation" section in RFC 6 and creates a new section on "disconnection", to sync up with how the disconnect RPC changed in flux-framework/flux-core#2913, and to describe the emerging practice for RPC cancellation.
> rfc3,6: add FLUX_MSGFLAG_NORESPONSE

- requirements.txt
This is needed to setup readthedocs. We could name the file something else (maybe `.requirements.txt` or `.github/requirements.txt` if we want to keep the top-level for the repo from having too many files.
> pip requirements file

- spec_26.rst
Needed proper RST format to link to other spec files.
> spec_26: fixup inter-doc links

- README.md
- conf.py
- index.rst
- requirements.txt
- spec_6.rst
This PR move the detailed RFC listing to the index file, which will appear as the top level page for RFC on readthedocs. This is entry page for users.
The README file is removed from sphinx processing. The README is now only used for indexing directly to source files on GitHub and providing information for developers.
This is a major change to the README, so I’d like a few people to review it before merging.
Closes #242 and Closes #234
> Index readme

- spec_20.rst
Problem: rfc20 is current written:
"The scheduling key allows RFC4-compliant schedulers
to serialize any subset of graph resource data into
its value and later deserialize this value
with no data loss. The scheduling key contains
a dictionary with a single key: graph.
Other keys are reserved for future extensions."
As such, we can't add addition keys under the
scheduling key.
As part of resource restruction work within fluxion,
we need to embed the queue name into RV1 so that
when fluxion qmanager is reloaded, it can
enqueue each currently running jobs into
the correct queue.
W/ this proposal, we can stick the queue name
to `scheduling.attributes.system.queue`.
> rfc20: add optional attributes key under scheduling

- index.rst
- spec_1.rst
- spec_10.rst
- spec_11.rst
- spec_12.rst
- spec_13.rst
- spec_14.rst
- spec_15.rst
- spec_16.rst
- spec_18.rst
- spec_19.rst
- spec_2.rst
- spec_20.rst
- spec_21.rst
- spec_22.rst
- spec_23.rst
- spec_24.rst
- spec_25.rst
- spec_26.rst
- spec_3.rst
- spec_4.rst
- spec_5.rst
- spec_6.rst
- spec_7.rst
- spec_8.rst
- spec_9.rst
This PR adds a github-visible comment which directs readers to view the rendered file on the readthedocs site.
Fixes #247
> GitHub comment for viewing ReST files

- Makefile
Thanks to @dhellmann (sphinx-contrib/spelling#52), we now get an error when there is a misspelling. 
This is part of a fix for flux-framework/flux-docs#43
> Misspellings cause make error

- README.md
- index.rst
- spec_21.rst
- spec_27.rst
- spell.en.pws
Here's a proposed RFC for a slight refinement of the protocol between the scheduler and job manager, heretofore only described at the top of [modules/job-manager/alloc.c](https://github.com/flux-framework/flux-core/blob/master/src/modules/job-manager/alloc.c), as promised in issue flux-framework/flux-core#2608 and discussed in PR flux-framework/flux-core#2960
I changed the `note` (string) key in the `alloc` response to `annotations` (object) in the ANNOTATE response only, leaving `note` (string) as is for SUCCESS and DENIED responses. Only ANNOTATE would update the job's hash of scheduler annotations.
> rfc27: Resource Allocation Protocol Version 1

- spec_27.rst
Per discussion flux-core issue #2608, when a job allocation
fails for any reason, the annotation shall be cleared.
> rfc27: Clear annotations on job alloc failure

- spec_19.rst
- spell.en.pws
As discussed in flux-framework/flux-core#3038, this PR proposes a standard alternate encoding for FLUIDs, most useful in decreasing the space required for JOBID output in tools such as `flux jobs`. I figured we'd get the idea down in the RFC so we could refer to it during development (assuming there is concensus).
> rfc19: propose a standard (alternate) encoding for FLUIDs

- spec_27.rst
Per some discussion in https://github.com/flux-framework/flux-core/issues/2608, instead of annotations being in a single flat namespace, have `sched` fields within a dictionary within the annotations.
Given choices in https://github.com/flux-framework/flux-core/pull/3065, add a `user` namespace/dictionary.
Not 100% sure if I used the right language (should I call it a `dictionary`?  an `object`? a `namespace`?)
> rfc27: Update per discussion and add new user namespace

- spec_27.rst
i think `queue` name is common enough we can go ahead and define it as a known special case
> rfc27: Add queue name as special case annotation

- spec_20.rst
- spell.en.pws
Currently we're working on adding support for carrying along hostnames instead of/in addition to ranks in flux-core. I started with adding the `"node"` key to `R_lite` object in `R`, but this will make every `R` on a normal system explode in size, since every rank entry in `R_lite` will now need to be separated.
This experimental addition to RFC 20 adds an alternative -- a `nodelist` key in the `execution` section of `R` version 1. If present, this key is a list of hostnames which directly correspond to the rank entries in the `R_lite` array. E.g. on a system where `fluke[0-16]` correspond to broker ranks `[0-16]`, and we have the `R`
```json
{"version":1,"execution":{"R_lite":[{"rank":"0,2-3","children":{"core":"0-3"}}]}},
```
Then `nodelist` would be `["fluke0","fluke2","fluke3"]`, i.e. …
> rfc20: replace R_lite "node" key with execution.nodelist

- README.md
- index.rst
- spec_29.rst
- spell.en.pws
While working on the addition of `nodelist` to the Rv1 format, it became apparent that what we really wanted were the "hostlist expressions" we've become used to.
In order to have something to which to refer, @garlick suggested we might want an RFC describing the Flux implementation of Hostlist, so here it is.
This is a rough draft, and I tried to keep it as short and simple as possible. Any suggestions for improvements are welcome.
> rfc29: Add RFC describing the hostlist format

- spec_20.rst
Update description of the Rv1 `nodelist` to allow "hostlists" instead of host sets.
Reference rfc 29 for definition of the hostlist format.
> rfc20: allow nodelist entries to use hostlist format

- .mergify.yml
Problem: The name of the travis-ci status check has changed with
the migration for travis-ci.org to travis-ci.com.
Update the name in the mergify config accordingly.
> mergify: update config after migration to travis-ci.com

- spec_27.rst
Add an RPC that allows the job manager to inform the scheduler of new priorities assigned to job(s) that have outstanding alloc requests.  It should be possible for the job manager to send _one_ of these requests to the scheduler after the fair share priority plugin finishes a batch of priority updates, so the scheduler receives the total order in one go.
This request would not be used in `single` mode.  In that case, if the single outstanding alloc request is no longer the highest priority job, the job manager must cancel its alloc request and let the top job take its place.
Also, the alloc request is modified to drop `t_submit` and redefine `priority` from the administrative priority to the queue priority.  (This assumes that the scheduler would no longer need the submit time because it …
> rfc27: add sched.prioritize RPC

- README.md
- index.rst
- spec_16.rst
- spec_18.rst
- spec_21.rst
- spec_27.rst
- spec_29.rst
- spec_30.rst
As discussed in flux-framework/flux-core#3377, the terms "queue priority" and "administrative priority" are a bit cumbersome/ambiguous.  This PR proposing changing the terms to "priority" and "urgency".
We had not written down the idea of urgency=0 for hold and urgency=31 for expedite so I went ahead and added a mini RFC about urgency and the meaning of these special values.  Hope that's not too much overkill.
> rename administrative priority to "urgency"

- spec_27.rst
Change the definition of the sched.alloc request to include
jobspec (minus environment), since that can now be trivially
included by the job manager, and will save a KVS lookup per job.
> rfc27: add jobspec to sched.alloc request

- spec_27.rst
Per discussion in https://github.com/flux-framework/flux-core/pull/3447, we will update the hello protocol to be a streaming RPC instead of a single request/response with an array of jobs.
I went back and forth on how to write the language for this section.  I'm still not 100% about it.
Also, I noticed that we never documented that `t_submit` is in the hello response.  So I added it.
> RFC27: Refactor hello RPC to be streaming

- spec_12.rst
Problem: RFC 12 description of overlay secrurity is out of date.
Explicitly mention CURVE and GSSAPI as reasonable ZMQ security methods,
instead of implying that anything but NONE is OK.
Describe the shared CURVE cert used by a system instance.
Describe the new CURVE public key exchange strategy for PMI-booted
Flux instances.
Drop the paragraph on security EPGM, as we don't support that anymore.
> rfc12: update overlay security with new PMI strategy

- spec_27.rst
Per issue https://github.com/flux-framework/flux-core/issues/2070, support mode=N in the `job-manager`.  Update RFC27 to allow a `mode=N` in the `sched.ready` protocol.
Not 100% if this is the best way to go about things, but thought I'd setup this PR for discussion / consideration of this change:
- should "mode" be an integer instead of a "string"?  We treat "unlimited" to mean 0 and obviously "single" is just numeral 1.  Seems silly to keep it a string.
- But we may want to keep as a string for future flexibility.  IMO, this is a good reason to keep it.
- Changing it to a numeral we'd have to break ABI in `libschedutil` in `flux-core`
- Another possibility, do we want to set `N` via an option?  So instead of `mode=2`, we could do `mode=N=2`.  Perhaps in the future we might want to do, …
> rfc27: support mode=limited in sched.ready

- spec_1.rst
- spec_2.rst
Some minor updates to RFC 1 and 2
* add forward references from RFC 1 to 2 and 7
* drop text about AUTHORS files we no longer use
* suggest the `Problem:` format for commit message bodies
> contributors: update some project practices

- README.md
- index.rst
- spec_10.rst
- spec_12.rst
- spec_3.rst
- spec_5.rst
- spec_6.rst
- spec_8.rst
- spec_9.rst
- spell.en.pws
This PR does two things, I'm fine breaking it up into separate PRs if desired.
1. Update outdated terminology similar to flux-framework/flux-core#3456
2. reword keepalive passages in RFC5 to de-emphasize running/sleeping transition keepalive messages
> remove outdated terminology, update keepalive description in RFC5

- spec_5.rst
This PR removes the FLUX_MODSTATE_SLEEPING state, which will no longer be applicable once broker modules don't send keepalive messages as they transition from SLEEPING (blocked in the reactor) to RUNNING.
> remove FLUX_MODSTATE_SLEEPING

- spec_21.rst
This simple addition to RFC21 allows management of dependencies via `dependency-add` and `dependency-remove` events. This enables some simple dependencies to be handled internally in the job manager, possibly via plugins. 
In the common case of no dependencies, there would be no change to existing behavior. If a job manager plugin wants to add a dependency to a job, it can issue the `dependency-add` event while in the depend state, e.g. via the `job.state.depend` callback. This will add a dependency reference to the job. When the job dependency is satisfied (e.g. at a future time, or when a job on which the job depends becomes inactive) the plugin can issue the `dependency-remove` event, the reference will be removed and the job manager will issue the `depend` event.
If a dependency …
> rfc21: add dependency-add/remove events

- spec_26.rst
- spell.en.pws
Since RFC 26 was originally written, it was decided to relax the dependency object spec so that only "scheme" and "value" keys were required.
I felt the document could benefit by adding a bit of background, especially calling out the new `dependency-add` and `dependency-remove` job events, and introducing the recent development of job manager plugins providing the hook for adding a new dependency scheme
Also, I added descriptions of the new simple dependency schemes proposed in flux-framework/flux-core#3696
I'm marking this as a WIP, indicating that it's sort of a straw man proposal and I'm happy to help rework it in another form or turn this PR over to others who have been working on the code and probably have deeper insights to offer.
> rfc26: add background, divide into sections, add simple dependencies

- spec_26.rst
Add "begin-time" to the list of built-in simple dependencies in RFC 26.
> rfc26: document built-in begin-time dependency

- spec_24.rst
Problem: It is unnecessarily restrictive to require that all data
events for a particular stream are bound to a single encoding. Allowing
the encoding to be overridden per-event would allow easy escaping
of invalid characters on a per-event basis. Knowledge that a data
stream cannot be encoded using the header-specified encoding may not
be known until runtime, at which point it is too late to go back and
change the encoding type.
Specify that any encoding specified in the header event is the
"default" encoding for a stream, implying that the encoding might
be overridden.
Allow an optional "encoding" key in the data context object. If set,
this encoding will be considered to override the default encoding
for that stream, and will apply to the current data event only.
Also see …
> rfc24: add optional encoding override in data events

- spec_26.rst
Problem: RFC 26 specifies that after:JOBID jobs start after the
antecedent enters the RUN state. However, it is more practical and useful
if dependent jobs are not started until the dependency also posts a
'start' event.
Update the language to indicate that dependent jobs with the 'after'
scheme are not started until the antecedent enters the RUN state *and*
a "start" event is posted.
> rfc26: after:JOBID jobs should start after start event

- spec_21.rst
Problem: No defined job event allows user data to be associated with
a job and captured in the eventlog for replay.
Add a "memo" event which associates generic data with a job.
New version of #304 with corrected branch name.
> rfc21: add memo event

- requirements.txt
- spec_2.rst
Per offline discussion about KubeFlux licensing needs, this relax the LGPL-3.0 REQUIRED language to RECOMMENDED for Flux framework projects.
Also, brought over a fix for rendering bullet lists on readthedocs from flux-docs, as I noticed they weren't rendering right here.
> rfc2: relax licensing

- .mergify.yml
Problem: mergify.io has deprecated the strict merge mode action:
https://blog.mergify.io/strict-mode-deprecation/
Replace the strict mode configuration with a default queue with a
rebase action which should be equivalent.
> mergify: replace strict merge with queue+rebase

- spec_15.rst
Problem: RFC 15 identifies the IMP executable as flux-security-imp,
but the IMP was implemented as simply flux-imp.
Update the name of flux-imp in the RFC.
> rfc15: change flux-security-imp to flux-imp

- .github/workflows/main.yml
- .mergify.yml
- spec_1.rst
- spec_10.rst
- spec_11.rst
- spec_12.rst
- spec_13.rst
- spec_14.rst
- spec_15.rst
- spec_16.rst
- spec_18.rst
- spec_19.rst
- spec_2.rst
- spec_21.rst
- spec_22.rst
- spec_23.rst
- spec_24.rst
- spec_25.rst
- spec_26.rst
- spec_27.rst
- spec_28.rst
- spec_29.rst
- spec_3.rst
- spec_30.rst
- spec_4.rst
- spec_5.rst
- spec_6.rst
- spec_7.rst
- spec_8.rst
- spec_9.rst
I found a couple typos in RFC 21. At the same time I regretfully ran `make linkcheck` and then was duty bound to fix all the broken links.
I added all the link fixes in one big commit (sorry)
Finally, added `make linkcheck` to ci. (So this will need to be merged manually).
> fix all broken links and a couple typos in RFC 21

- spec_3.rst
- spec_5.rst
- spec_7.rst
- spell.en.pws
Problem: it's going to be confusing having both application level "keepalives" (not even really named properly for how they are now used) and TCP keepalives in configuration, etc..
Rename keepalives to "control messages".
Update module rfc to describe regular RPCs instead of keepalive use for this purpose, as proposed in flux-framework/flux-core#4110.
If accepted, another flux-core PR would switch the broker over to using "control messages".
> rename keepalives to control messages

- README.md
- index.rst
- spec_20.rst
- spec_31.rst
Problem: Rv1 does not support a method for assigning properties to
resources, but simple property support is a near term requirement for
Flux.
Add an optional `properties` key to the Rv1 `execution` dictionary which
allows for the simple assignment of named properties to sets of ranks.
> rfc20: add optional execution.properties key to Rv1

- spec_14.rst
Problem: RFC 14 defines a jobspec duration of 0 as being unset or
unlimited, but does not specify further what that means. This could
allow different scheduler implementations to drift in how they apply
time limits when no duration is specified.
Add wording that explicitly indicates how a scheduler should treat an
unset duration.
> rfc14: update definition of duration=0

- data/spec_14/schema.json
- spec_14.rst
Problem: RFC 31 defines a format for specification of generic job
constraints, but RFC 14 does not define the location for a constraints
in jobspec.
Define attributes.system.constraints as the location in jobspec for
RFC 31 defined constraints.
> rfc14: add constraints attribute to jobspec

- spec_20.rst
Problem: The purpose of the scheduler-specific `@` character in
property strings is vague in RFC 20, and could cause confusion.
Expand the description of the purpose and possible use case for `@`
in execution target properties. Specify that the literal property
string shall still apply to the execution target, but the scheduler
implementation may use all or part of the prefix and suffix before the
`@` for scheduler specific optimizations.
> rfc20: expand description of scheduler specific properties

- spec_10.rst
- spec_11.rst
While working on flux-framework/flux-core#4208, I referred to RFC 10 and 11 and found a few deficiencies.  This is an attempt to bring them up to date.
> update  content/KVS RFCs

- spec_25.rst
As discussed in flux-framework/flux-core#4228, we should have limited support for the `exclusive` flag on `node` resources in jobspec v1.
This PR simply adds that as a first step.
The next step will be to add a method to set this flag in the `Jobspec` class of Python and a new flag in `flux mini` tools to set it explicitly, and finally setting it implicitly when only `-N` is used. I guess we'd also want to add support for this flag in `libjobspec1` and the various jobspec C parsers in flux-core.
At first, `sched-simple` will just reject jobs when this flag is set. We're actually in a pretty good place since `-N` without `-n` was an error before, we are guaranteed to not break any tests. So kudos to @garlick and @trws for suggesting this behavior at first, since it will save a lot of pain …
> rfc25: add optional exclusive key to node resource vertex

- spec_10.rst
Fix typo in RFC 10 caught by @chu11 after PR was merged.
> rfc10: fix typo

- data/spec_14/use_case_2.9.yaml
- spec_14.rst
- spec_25.rst
As described in #319, the lack of an example and references for the `constraints` key makes searching the RFC for this support challenging. Also references for `constraints` and `dependencies` is missing from RFC 25 (Jobspec v1 definition).
This PR addresses these concerns.
Fixes #319
> rfc14,25: add example and references for constraints, dependencies

- conf.py
- spec_23.rst
Problem: The Flux Standard Duration specification only allows a unit
suffix of "s" (seconds) or greater, but there are times when it would
convenient to represent a duration in milliseconds (ms), especially
when converting a small duration into FSD.
Add an "ms" suffix to the FSD spec. Reword the specification to allow
for string suffixes instead of only a single character suffix.
> rfc23: add "ms" suffix to Flux Standard Duration

- README.md
- index.rst
- spec_32.rst
This documents the current protocol used between the job manager and the job execution system, as a precursor to reworking the job execution service.  @grondo already had RFC 32 in progress so I skipped to RFC 33.
> add new RFC for job execution protocol

- spec_28.rst
This PR is a first stab at an extension to the resource acquire protocol which would allow dynamic addition and removal of execution target properties.
The end result of such an extension might be a `flux resource property add/remove` command, which could end up being useful in even single-user instances of Flux (e.g. if a workflow wants to partition resources in some way, detects slow vs fast nodes, mark nodes on which a job ran for data locality, etc.)
This is just a proposal at this point. Feel free to discuss the implementation here.
One drawback to adding new keys to the `resource.acquire` response stream payload is that a scheduler could just ignore these new keys and `flux resource property add/remove` would silently do nothing. Perhaps the scheduler should additionally have some …
> rfc28: add property-add, property-remove keys

- spec_10.rst
- spell.en.pws
This changes the content load and store message definitions to carry raw hash digests rather than blobrefs, which reduces message size and processing overhead slightly.  This simplification is possible because we no longer expect to need to support multiple hash algorithms within a given instance, nor sharing of raw content between instances.  Also, we have restricted access by guests and recast the service as a KVS layer rather than general purpose.
It also feels like protocol cleanup, given that the blobref strings are being sent as raw payload.  If we're not sending them as strings within a JSON object, why not just send the more space efficient raw representation?
I also added some info that fills out this rather sparse RFC a bit.
I do have a prototype branch which implements these …
> rfc10: use hash digests in raw message payloads not blobrefs

- README.md
- index.rst
- spec_33.rst
- spell.en.pws
Per discussion in yesterday's meeting and in #331, here's a proposed skeletal RFC on queues and some initial content designed to provoke discussion.  The goal was to strip down the prose and tie the design to the use cases proposed by @ryanday36.  I'm not sure I got there, especially on that last point, although it was making sense in my head.
This proposes that we make queues (plural) a first class abstraction in Flux, and that we let each queue have its own priority domain, scheduling algorithm, limits, access policies, etc..
It proposes that there is one default queue named **main** that is a stand-in for the current single anonymous queue, which you get for free without configuration.
Just remembered a couple of things I forgot, but I'll leave them off for now and give others a chance …
> rfc33: add queues RFC

- spec_21.rst
Problem: RFC 33 refers to the `jobspec-update` event in RFC 21, but it does not appear there.
Add the event to RFC 21.
> RFC21: add jobspec-update event

- spec_19.rst
Problem: Lower case f was listed twice:
"lowercase f ``f``"
Solution: list the lower case f just once!
> rfc19: fix English error / typo

- spec_10.rst
- spec_33.rst
Problem:  The design for applying jobspec defaults and implementing limits has evolved somewhat since the RFC was written.  In addition, some notes were placed there during discussions that were thought would be ongoing, but which did not go anywhere.
Make a pass through RFC 33 to get it in sync with current plans.
> rfc33: update after implementing limits and jobspec defaults

- index.rst
- spec_21.rst
Problem: the job eventlog format recently changed with the addition
of the validate event, and this made it difficult to detect and
handle eventlogs from earlier versions when restarting after a
Flux upgrade.
Add a version number to the submit event that can be used to
distinguish this and future changes to the eventlog format.
See also flux-framework/flux-core#4399
> rfc21: add version to submit event

- spec_33.rst
Problem: RFC 33 specifies that queue.NAME.requires may refer to advanced RFC 31 constraint specifications, but these are not yet implemented and may be confusing for admins to configure.
Re-define queue.NAME.requires as an array of property constraint names.
> rfc33: simplify queue.NAME.requires

- spec_13.rst
Problem: There is no PMI_process_mapping example for "cyclic" task distribution, and the fact that rank to nodeid assignment can be determined is not entirely clear from the prose (but obvious given the goal of finding "cliques" for shmem communication).
Mention that the rank to nodeid assignment can be determined from the mapping.
Add an example of cyclic task distribution, and update formatting and descriptions of the other examples for clarity.
> rfc13: elaborate on PMI_process_mapping

- spec_13.rst
Problem: one of the PMI_process_mapping examples recently expanded has the wrong rank lists.    Also, this document  is egregiously malformatted.
Fix the example and spruce up the formatting a bit.
> rfc13: fix PMI_process_mapping example + improve formatting

- README.md
- index.rst
- spec_34.rst
- spell.en.pws
Problem: Flux needs a task map format that scales for both block and cyclic task distributions.
Define a new format in rfc34.
> rfc34: add flux task map RFC

- spec_34.rst
RFC 34 does not indicate how to specify an unknown task mapping, but indication of an unknown mapping is required when, for example, an encoded mapping is too large to distribute or the mapping is otherwise not known.
This PR documents that an empty string is an indicator of an "uknonwn" mapping for `PMI_process_mapping`, as is already documented in RFC 13, and also makes an empty string the official encoding of an unknown mapping in the Flux Task Map format.
Additionally, an "empty" mapping is also allowed by changing the task map requirement from "one or more blocks" to "zero or more". (This is probably only useful in testing, and also is the encoded output from a libtaskmap encoded result from `taskmap_create()` with no further initialization)
> rfc34: allow empty and document unknown task maps

- .github/workflows/main.yml
- spec_13.rst
Just a bit of cleanup in RFC 13 which I had been referring to lately.  Now the  PMI function defintions look more like Jansson's API docs!
> rfc13: use function directive to make PMI API docs more readable

- spec_23.rst
Problem: There are times when a duration must be encoded as infinity or unlimited, but FSD does not offer a good way to express that.
Support the string "infinity" as a special case in RFC 23.
> rfc23: support infinity as valid FSD

- spec_3.rst
- spell.en.pws
Problem: RFC 3 is wishy washy about byte order within the PROTO frame.
Drop an incorrect statement from a figure caption, and replace incomplete comments in the ABNF wtih a definitive statement in the prose.
> RFC 3: clarify byte order of 32-bit integers in PROTO frame

- spec_31.rst
Now that we're close to supporting conditional operators and `hostlist` and `ranks` in Fluxion and sched-simple, update the RFC to require these operators be supported for a scheduler to be RFC 31 compliant.
> rfc31: update Job Constraint Specification

- README.md
- index.rst
- spec_31.rst
- spec_35.rst
A simple "mini language" for generating RFC 31 style JSON "constraint" objects has been proposed in a couple different experimental PRs (flux-framework/flux-core#4677 and flux-framework/flux-core#4849). Therefore it seemed like a good idea to formalize the proposed syntax in an RFC.
This is a WIP to allow others to comment and approve of the general syntax being proposed. It should be noted that the proposal is inspired by existing search/query syntax in tools like Google search, Gmail and [Apache Lucene](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html), which should make it familiar to most users.
> rfc35: add RFC describing a simple string-based syntax for generating RFC 31 constraint objects

- spec_21.rst
Problem: There is ambiguity in RFC 21 about the inclusion of extra events and context keys beyond those specified in the document.
Add a couple statements that make it clear that additional events and context keys are allowed.
> rfc21: remove ambiguity about extra events and context keys

- README.md
- index.rst
- spec_36.rst
- spell.en.pws
This WIP RFC formalizes a method for embedding submission utility options in a file or script, for example to satisfy flux-framework/flux-core#3957. The proposed _submission directive_ specification was designed with the following in mind:
* Allow directives in something similar to the "pragma style" used by traditional batch systems to maximize user familiarity
* Do not make any assumptions about the quoting style of the source file or script
* Encourage directives to be placed together in a source file
* Allow easy and familiar quoting of directive arguments
* Leave the specification open for future extensions
There are some examples in the last section of the proposed RFC.
> rfc36: add RFC describing submission directives

- spec_36.rst
Problem: One of the examples in RFC 36 is invalid because it does not include the directive sentinel for all lines of a multiline quoted string.
Fix the invalid example to comply with the RFC.
Also fix a minor typo in another example.
> rfc36: fix invalid example

- README.md
- index.rst
- spec_37.rst
- spell.en.pws
Problem: flux-filemap(1) and the stage-in shell plugin use a first draft of a JSON file archive format, and now we need something similar for embedding input files in jobspec.
Add an RFC proposing a format that would work for both.
> rfc37: add File Archive Format RFC

- requirements.txt
- spec_14.rst
- spec_25.rst
Problem: "queue" is a common system attribute but is not listed.
Add it.
> rfc14/25: add queue to common system attributes list

- spec_24.rst
Problem: when a job produces many identical lines of output, such as when repeatedly encountering the same error, we have no way of representing that efficiently in the output eventlog.
Add a repeat key to data events.
Identical data items can be de-duplicated when added to the eventlog, and re-duplicated when converted back into a stream.
> rfc24: add repeat key to data event

- spec_12.rst
Add a new role to indicate that a message is local vs remote.
This goes along with code proposed in flux-framework/flux-core#5162.
> rfc12: add FLUX_ROLE_LOCAL

- spec_14.rst
- spell.en.pws
Problem; There is no standardized method for embedding files in jobspec.  Currently, `flux batch` and the job shell use an ad-hoc mechanism to store the batch script under `attributes.system.batch.script`, but it would be useful to formalize this case and open the door for the storage of other simple files in jobspec, with automated extraction by the job shell.
Document `attributes.system.files` as an RFC 37 file archive, which shall be extracted by the job shell into the job's temporary directory. Reserve two files: `script` for any job batch script, and `conf.json` for a subinstance config file.
This PR is currently a WIP while a prototype of the job shell and cli interface are developed. We can also start a discussion to make sure all use cases are covered with this simple proposal.
> rfc14: add `files` section to jobspec

- spec_21.rst
Problem: Currently the exception note is defined as optional.  Making the exception note optional makes parsing exceptions difficult.
Solution: Make an exception note required.  If one is not desired, it should be set to an empty string.
---
per discussion in https://github.com/flux-framework/flux-core/pull/5336
I went with the language "should" set it to empty string.  Because implementation could choose something different, eg. "no note specified", etc.
> rfc21: make exception note required

- spec_21.rst
Problem: there is no way to update the expiration time in R once allocated.
Add a resource-update event similar to jobpspec-update. Currently the only allowed context key is expiration but this could be expanded in the future.
> rfc21: add resource-update event

- spec_27.rst
Problem: there is no way for the job manager to notify the scheduler that a job's expiration has been adjusted, nor for the scheduler to fail such a request if it would interfere with an advance reservation.
Add the sched.expiration RPC.
> rfc27: add sched.expiration RPC

- README.md
- index.rst
- spec_38.rst
- spell.en.pws
Problem: the key-value format used by flux-security ostensibly for auditability is not documented.
Add an RFC.
> rfc38: add rfc for flux-security key-value encoding

- README.md
- index.rst
- spec_39.rst
Problem: flux security signature format is undocumented.
This is a work in progress RFC that attempts to document the format.
> add RFC for Flux security signatures

- spec_21.rst
Problem: the jobspec-update event is constrained to only allow updates to the `attributes` section, but updates to the resources section are needed to implement emerging requirements in flux-coral2.
Allow any key to be updated.
Add some clarity on JSON key "paths" and what is supposed to happen if the key already exists.
Fixes #395
> rfc21: allow jobspec-update to any key

- spec_23.rst
Problem: In commit
7eca38c882c8acc6b8e0a5c61cbab41a548060af
a list of suffixes was converted into a table.  This conversion accidentally dropped a note indicating that the default units of FSD are in seconds.
Solution: Add a sentence after the suffix table indicating the default is in seconds if no suffix is specified.
> rfc23: note default fsd is in seconds

- .readthedocs.yaml
- spec_13.rst
Problem: PMI-1 API documentation formats function parameters as literals, rendered in red monospace.
Use `:c:var:` instead.
Fix up a couple of other minor formatting problems along the way.
>  rfc13: fix formatting of C API docs

- spec_28.rst
Problem: RFC 21 defines a resource-update event which may modify the expiration time of the R for a job, but there is no way for an expiration update of a Flux instance running as a job to be communicated to the subinstance scheduler.
Add an expiration key to the RFC 28 acquire response which may be used by the instance reosurce module to notify the scheduler of an expiration update.
This approach was taken for now instead of a more generic extension to the acquire protocol (e.g. grow/shrink, etc) because this will be simplest to implement. A more generic extension to support future grow and shrink probably needs more thought and design.
> rfc28: add expiration to list of possible keys in acquire response

- README.md
- index.rst
- spec_20.rst
- spec_40.rst
- spell.en.pws
Problem: the detailed description of Fluxion's scheduling key format is inappropriate in RFC 20 which describes the general Rv1 format.
Pull it out to a new RFC 40.
Also, improve the markup in RFC 20 to make it more readable.
> rfc40: pull fluxion scheduling key def out of rfc20 and reformat rfc20

- spec_20.rst
- spell.en.pws
RFC 20 contained a lot of prose that didn't really add clarity, and missed explicitly mentioning some requirements.
Rework the RFC so that it's more useful as a quick reference and includes clarifying points that were missing.
> rfc20: rework content

- README.md
- index.rst
- spec_41.rst
- spell.en.pws
Problem: job-info services are not documented.
Add an RFC to document the `job-info.lookup` RPC, for start of discussions on potential changes.
> rfc41: add new RFC for job information service

- README.md
- index.rst
- spec_42.rst
- spell.en.pws
Problem: the subprocess execution protocol is not documented.
Add a new RFC.
(Marking as a WIP since I think I need to make another pass double-checking this against code before unleashing it on others)
> rfc42: add subprocess protocol RFC

- README.md
- index.rst
- spec_43.rst
- spell.en.pws
Problem: job-list services are not documented.
Add an RFC to document current RPCs.
---
first run through, I might have some rst-isms wrong. But mostly went back and forth on various wording and various layout.  Lets see what initial reaction is :P
> rfc43: add new RFC for job list service

- spec_43.rst
- spell.en.pws
Problem: A caller has the ability to specify an unbounded sized constraint object, which could serve as a denial of service (DoS) attack on the job list service.
Specify hard constraint limits on the size of operator arrays and constraint depth.
----
initial proposal based on https://github.com/flux-framework/flux-core/pull/5681
> rfc43: add constraint DoS limits

- spec_41.rst
- spell.en.pws
Problem: The job-info.lookup RPC is missing new flags that are supported.
Document the new flags.
---
WIP as we discuss https://github.com/flux-framework/flux-core/pull/5633 ("update" vs "updated" as flag name?)
also .. this specific spec change assumes https://github.com/flux-framework/flux-core/pull/5635 would go in too.  Could break into two commits.
> rfc41: add new lookup flags

- spec_14.rst
- spec_25.rst
- spec_27.rst
- spell.en.pws
Problem: flux-framework/flux-core#5783 adds R to the sched.free request to avoid an extra lookup.
Add R to the sched.free request payload definition in RFC 27.
> rfc27: add R to sched.free request

- spec_27.rst
Problem: sched.free requires a response, but this adds complexity to the job manager and has little benefit.
Code that drops the sched.free response from flux-core is proposed in flux-framework/flux-core#5786.
Drop the free response.
> rfc27: eliminate sched.free response

- spec_42.rst
Problem: while tracking down flux-framework/flux-core#5956, it became evident that RFC 42 does not specify which responses must be expected in a successful exec stream.
Add a paragraph that clarifies this.
Also add a couple of other minor cleanups.
> rfc42: note response requirements for a successful exec stream, plus cleanup

- spec_42.rst
Problem: requiring the PID as a parameter to `write` complicates client code which must support writing/closing a stream before the `started` response has been received.
Use the `exec` request matchtag instead.
Note: this came up while discussing flux-framework/flux-core#6002
> rfc42: exec.write should use matchtag not pid

- spec_43.rst
Problem: A hostlist constraint operator is defined in the set of supported job-list constraint operators, but there is no corresponding ranks constraint.  The ranks constraint is useful not only in test instances where multiple ranks may share the same hostname, but also in cases where a specific rank is to be queried without dependence on hostname (e.g. rank 0).
Define a supported `ranks` constraint operator in RFC 43.
> rfc43: add job-list 'ranks' constraint

- conf.py
- spec_14.rst
Problem: The canonical jobspec attributes for `bank` and `project` are not specified in RFC 14. Even though these attributes only apply for multi-user instances with an accounting plugin configured, they are common enough concepts that it would be useful to standardize their name, location in jobspec, and purpose.
Define `bank` and `project` attributes in RFC 14. Add a note that these attributes may have no effect unless an accounting package is installed and configured.
> rfc14: add bank and project as optional jobspec attributes

- spec_27.rst
Problem: there is no mechanism for a job's resources to be released in phases.
Allow multiple sched.free quests per job.  Add an optional `final' flag to the last sched.free request for each job as a hint to the scheduler, as discussed in flux-framework/flux-core#6179.
> rfc27: support partial release

- spec_5.rst
Problem: flux-framework/flux-core#6203 proposes to change the topic strings used for the module management RPCs.
Update the topic strings mentioned (somewhat superfluously) in the RFC.
> rfc5: update module managment topic strings

- conf.py
- spec_27.rst
- spell.en.pws
This is a first cut at documenting the ``feasibilty`` service proposed in #384.
Fixes #384
> rfc27: document job feasibility service

- spec_15.rst
- spell.en.pws
Problem:  RFC 15 only describes `flux imp kill` but we need the IMP to forward signals.
Take a stab at describing this behavior, admittedly without a lot of detail as yet - perhaps we can fix that by coming to some agreement on those details.  But this is a start anyway.
> rfc15: describe IMP signal handling + minor updates

- spec_15.rst
Problem: we've added `flux imp run` and `flux imp kill` but these are not described in RFC 15.
Describe `flux imp run`.
Instead of describing `flux imp kill`, propose a simplification where `flux imp run` lingers and forwards signals, analogous to the way `flux imp exec` was proposed to do for the shell.
There's also a bit of unrelated cleanup for RFC 15, split into separate commits.
> rfc15: describe flux imp run and how these processes are to be killed

- spec_42.rst
- spell.en.pws
Problem: rfc42 does not specify anything about channel flow control, so it is difficult to design clients and servers that operate without dropping data.
Add credit based flow control to the protocol.
The client receives credit for writes to the subprocess via the exec add-credit response.
The server receives credit for output to the client via the add-credit RPC.
> rfc42: add credit based flow control for channels

- spec_15.rst
Problem: RFC 15 states that the IMP may exit after the job shell exits, but then it cannot forward SIGUSR1->SIGKILL to stuck processes if the shell exits early.
Change the wording to allow the imp to linger after the shell exits.
> rfc15: IMP may linger post-shell to clean cgroup

- spec_14.rst
- spec_25.rst
- spell.en.pws
Problem: jobspec has no way to express preemptibility
Add the preemptible-after jobspec attribute.
> RFC 14,25: add preemptible-after system attribute

- spec_27.rst
This adds a `partial-ok` flag to the hello request, and (if that flag was true) an optional `allocated` idset key to the response which can indicate which ranks of R are allocated when some of the ranks have already been released.
The problem has been discussed in flux-framework/flux-core#6089
> rfc27: support partial hello responses

- spec_7.rst
Problem: We've adopted a defacto guideline that long test expressions connected by "AND" or "OR" operators should be broken to one test expression per line.  This is not documented.
Add this to RFC 7.
> rfc7: break long test expressions to one per line

- spec_24.rst
Problem: "OPTIONAL" is misspelled.
Spell it correctly.
> rfc24: fix a typo

- spec_1.rst
- spec_20.rst
Problem: the wording on how ranks and hostnames are ordered in R_lite is possibly a bit ambiguous, as discussed in flux-framework/flux-core#6584.
Make it very clear that the hostnames are in execution target rank order rather than the R_lite array order.
> rfc20: clarify R_lite rank:host mapping

- README.md
- index.rst
- spec_44.rst
- spell.en.pws
Problem: resource events are not defined
Add an RFC that defines the current events and a journal service for streaming events from the resource module.
> rfc44: add rfc for resource.eventlog

- spec_14.rst
Problem: the acceptable values for the keys within a resource range dictionary are not entirely clear from the text, and some behaviour differs between flux-core and flux-sched
Firstly, once I started testing some resource ranges, it's clear that having an operand of 1 for either the '*' or '^' operators is nonsensical, since min*1 or min^1 don't change anything. Also for the '^' operator having min==1 is nonsensical, since 1^operand also goes nowhere. However, once I got looking at the implementation in flux-sched, I noticed that if an operand of 1 is given with either the '*' or '^' operators, there is an if statement which simply short circuits to return the min value. I personally think this is non-intuitive behaviour; it feels to me like such nonsensical input is likely an …
> rfc14: clarify resource range keys restrictions and/or default behaviour

- spec_44.rst
Problem: RFC 44 does not provide for the possibility of truncating the resource journal of events.
Add a truncate event to RFC 44 for this purpose.
> rfc44: add truncate event

- spec_44.rst
Problem: At least one documented use case could make use of a reason field in the undrain event, but RFC 44 does not allow that.
Add an optional reason key in the undrain context.
> rfc44: add optional reason field to undrain event

- spec_28.rst
This PR adds the `shrink` key to RFC 28 as suggested in flux-framework/flux-core#6641.
This key contains an idset of execution targets which have been removed from the instance so should no longer be considered for scheduling.
> RFC 28: add `shrink` key to resource acquisition response

- spec_1.rst
Problem: our fork of C4 lists commit message titles and bodies as optional, but in practice we require message bodies for flux-framework patches.
Update RFC 1 to reflect this.
Fixes #448
> rfc1: require commit message titles and bodies

- Makefile
- data/spec_14/schema.json
- data/spec_25/schema.json
- spec_14.rst
- spec_25.rst
Problem: the "Tasks" section of RFC 25 basically just points back to RFC 14, but in my testing there does seem to be several noteworthy restrictions on the "count" key that I couldn't find documented anywhere.
This PR is basically my attempt at clarifying what I would have found useful to have in the documentation, based on my best understanding of how the keys seem to behave in my testing. My apologies if I'm not totally correct on the true behavior, but hopefully it won't be too difficult for someone with more knowledge than me to tweak the wordings if necessary!
> rfc25: clarify V1 restrictions in tasks section

- spec_7.rst
Problem: link to kernel coding style documentation is out-of-date
Update link to point directly to correct location
> rfc7: update link to kernel coding style standard

- conf.py
Problem: Access to https://www.mcs.anl.gov gets 403 Forbidden with `make linkcheck` in CI.
Add this URL to the ignore list for linkcheck.
Fixes #456
> conf.py: ignore anl.gov in linkcheck

- README.md
- data/spec_14/schema.json
- data/spec_14/use_case_1.8.yaml
- index.rst
- spec_14.rst
- spec_45.rst
Problem: irregular ranges of resource counts that do not fit the current min/max/operator/operand paradigm cannot be specified.
Allow a third option (in addition to single integer and range dict) for resource counts to be a string containing an RFC22 idset of acceptable counts.
Obviously new operators could be defined for some cases (including the simple example I included), but for future-proofing it would seem desirable to have a fallback for users to specify any arbitrary set of counts they desire.
[SLURM allows similar strings for its node counts](https://slurm.schedmd.com/salloc.html#OPT_nodes) so this would ensure flux ends up at least as capable as SLURM in this regard ;)
(idset regex created/tested via https://regex101.com/r/65FyDf)
> rfc14: allow idset and range strings for resource count

- spec_35.rst
Problem: there is a lexer warning in `make html` when using EBNF for the grammar and it doesn't render well on readthedocs
Swap EBNF for PEG and tweak to match actual definitions used in `flux-core/src/bindings/python/flux/constraint/parser.py`
This could be totally wrong or out-of-line, in which case sorry! But this warning just irked me when I was building things, so I was trying to figure what might make more sense, and PEG seemed to fit better than EBNF? The explicit forward slashes to indicate regex also didn't play well with the syntax highlighting, and seemed to be an implicit part of such a grammar specification anyway (and aren't in the strings actually used in constraint.py) but feel free to edit as desired :)
> rfc35: fix grammar syntax highlighting

- README.md
- index.rst
- spec_46.rst
- spell.en.pws
Problem: we cannot define arbitrary jobspec resources lists easily on the command line
Define a compact string representation that can be mapped to a full jobspec resources request
Apologies for stepping on any toes, but I was reading through @vsoch's draft in #371 and the discussion in flux-framework/flux-core#2213 and this idea started forming in my head, and wouldn't leave me alone until I had written it down, and then it snowballed into this, hahaha!
I'm not sure if people are still interested in this feature or not, but figured I'd open the PR in any case. And I think my main takeaway would be that whatever is settled on it shouldn't be V1 specific, otherwise it's just one more thing that needs to be transitioned eventually. This syntax makes simple requests very simple and compact, …
> command line jobspec resources (alternative to PR 371)

- spec_14.rst
Problem: the 'with' key in a resource vertex dictionary should be a list of dictionaries, not just a dictionary.
Update the text to clarify the type specification.
> rfc14: resource 'with' key should be a list

- .mergify.yml
Problem: The condition in the mergify config which attempts to prevent WIP PRs from being merged has an incorrect regex.
Rewrite the regex without quotes so it will match PR titles. Simplify the expression using a case insensitive match, and only match one or zero brackets instead of zero or more.
> mergify: fix wip regex
