flux-framework/rfc

spec_8.adoc

Let's open up a *pending* PR for rfc8. We can capture required changes to the document here for merging into flux-framework/rfc. Once we've got something most people are happy with, 
someone can merge the doc...

rfc8: Initial rough draft for the Flux Program Interface rfc

---

spec_9.adoc

This is currently a bullet-list of patterns and anti-patterns as we have touched on them.  It could probably benefit from references to issues where either the patterns or anti-patterns have shown up.  Treat this as a comment draft, and let me know what you think.

first draft of a best practices RFC on synchronization mechanisms in flux

---

README.adoc
spec_1.adoc

Amend C4.1 per issue #27
Does this capture the main things we wanted?

add some patch requirements to C4.1

---

spec_4.adoc

This addresses rfc [Issue 25](https://github.com/flux-framework/rfc/issues/25) and organizes the ideas and recommendations generated in a Feb 2015 email discussion.

rfc: Add resource request and annotation guidance to RFC 4.

---

.travis.yml
spell.en.pws

Building on @garlick's #43, run `make check` under travis in case we forget to do it when creating a new PR.

run 'make check' in travis-ci for pushes and pull requests

---

spec_14.adoc
spell.en.pws

Came across this reference a while back, but today I thought we should include it as a reference we have seen.

spec_14:  Add JSDL reference

---

spec_14.adoc

Fix a few minor typos.  No change in content.

rfc14:  fix minor typos

---

spec_14.adoc
spec_15.adoc
spell.en.pws

Unsure how these problems crept in, but spellcheck complains unless
they are fixed.

rfc:  spell check fixes

---

data/spec_14/use_case_1.3.yaml
data/spec_14/use_case_1.4.yaml

Fix some bugs in the use case examples.

rfc14: fix use case yaml examples

---

spec_16.adoc

This builds on pr #114 as discussed there.

rfc16: clarify who creates/destroys guest namespace and content

---

spec_14.adoc
spell.en.pws

rfc14: change static references to asciidoc footnotes

---

Makefile
README.adoc
indexcheck

A link to RFC 18 from the front page is needed.

README.md: add link to RFC 18

---

spec_11.adoc

per discussion in https://github.com/flux-framework/flux-core/issues/1860

rfc11: add symlink namespace support

---

Makefile
README.adoc
spec_20.adoc
spell.en.pws

This PR adds a new RFC that specifies the format 1 of resource set specification. This is discussed and agreed at https://github.com/flux-framework/rfc/issues/109#issuecomment-460469688.

RFC20: Add Resource Set Specification RFC

---

spec_14.adoc
spell.en.pws

This PR links the jobspec RFC to the new RFC 20 and also addresses https://github.com/flux-framework/rfc/pull/151#issuecomment-461153941.

RFC14: Link to RFC20 and clarify the semantics of count

---

spec_21.adoc

Update events described in RFC 21 to conform with
changes just merged in RFC 18.

rfc21: convert events to JSON

---

spec_14.adoc

Not 100% sure of how I worded things.  It's atleast "pretty good", but maybe not perfect.
Fixes #216

rfc14: Document system.shell/system.shell.options

---

README.md
index.rst
spec_14.rst
spec_26.rst

rfc26: re-add after dropping it during conversion

---

spec_12.rst

Problem: the Flux security design has replaced the original
"user database" with configuration, but RFC 12 was not updated.
Update the RFC.
Fixes #257

rfc12: drop user database

---

README.md
index.rst
spec_28.rst
spell.en.pws

This documents the current protocol in use between scheduler and resource module.

rfc28: add resource acquisition RFC

---

.github/workflows/main.yml
index.rst

This PR just addresses a couple small items:
* do not run pr-validator except for PRs
* add missing reference to RFC 31 in index

fix a couple small issues

---

spec_16.rst
spec_31.rst

Just noticed a couple of things were amiss when perusing these RFCs.

fix a couple typos

---

spec_32.rst

Per discussion in #327, fix some minor gotchas that were missed.

rfc32: minor fixes

---

spec_3.rst

Problem: when a client communicates with Flux over a UNIX domain socket, a single byte is returned upon connection that indicates whether the connection is authorized.  This is not described in any RFC.
Rework the Message Framing section as Message Framing and Security, and describe this initial handshake.
Fixes #347

rfc3: describe authorization handshake

---

data/spec_20/example1.json
spec_20.rst

A few times I've wanted a simple example and end up digging one up out of an active Flux instance instead.  Add a basic R example into rfc20.
Would be great if there were a few more advanced ones with more of the optional keys, but not too familiar with them.  Hopefully this is a starting point.

rfc20: add basic R example

---

spec_31.rst

This is a proposal for clarifications on #375 and #376.  I'm not sure if this will be liked or not, but could atleast start a discussion.

rfc31: add clarification on several corner case / use cases
